# Generated by Django 2.2.5 on 2019-10-22 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='children',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsidiaries', to='brands_app.Company'),
        ),
    ]
