# Generated by Django 2.2.5 on 2019-10-22 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands_app', '0002_company_children'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='favorite_brand',
            new_name='favorite_brands',
        ),
        migrations.RemoveField(
            model_name='company',
            name='children',
        ),
    ]
