# Generated by Django 2.2.5 on 2019-10-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands_app', '0004_auto_20191028_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='cid',
            field=models.CharField(default='Open Secrets CID', max_length=100),
        ),
    ]
