# Generated by Django 2.2.5 on 2019-10-28 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands_app', '0005_politician_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='img_url',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='company',
            name='cid',
            field=models.CharField(default='', max_length=200),
        ),
    ]
