# Generated by Django 2.2.5 on 2019-10-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands_app', '0006_auto_20191028_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='img_url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
