# Generated by Django 2.2.5 on 2019-10-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands_app', '0006_auto_20191028_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politician',
            name='assumed_office',
            field=models.DateTimeField(),
        ),
    ]
