# Generated by Django 2.2.5 on 2019-10-30 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands_app', '0007_auto_20191030_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lobbyist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PAC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.CharField(default='2020', max_length=10)),
                ('total', models.IntegerField(default=0)),
                ('lobbyist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands_app.Lobbyist')),
                ('pacs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands_app.PAC')),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands_app.Politician')),
            ],
        ),
    ]
