# Generated by Django 2.2.5 on 2019-10-30 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands_app', '0007_company_img_url'),
        ('brands_app', '0009_company_donations'),
    ]

    operations = [
    ]
