# Generated by Django 2.2.5 on 2019-11-01 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands_app', '0013_auto_20191031_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='lobbyist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brands_app.Lobbyist'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pacs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brands_app.PAC'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='politician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brands_app.Politician'),
        ),
        migrations.AlterField(
            model_name='politician',
            name='assumed_office',
            field=models.CharField(max_length=50),
        ),
    ]
